name: CI
on:
  push:
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node_version: [16, 18, 20]
        include:
          # Active LTS + other OS
          - os: macos-latest
            node_version: 18
          - os: windows-latest
            node_version: 18.17
      fail-fast: false
    name: 'Build&Test: node-${{ matrix.node_version }}, ${{ matrix.os }}'
    steps:
    - uses: actions/checkout@v3
    - uses: pnpm/action-setup@v2
      with:
        version: 8
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'
    - name: Install dependencies
      run: pnpm install
    - name: Test Packages
      run: pnpm test
